In [1]:
import pandas as pd
import numpy as np
import matplotlib as plt
import seaborn as sns
from datetime import datetime as dt

In [2]:
df = pd.read_csv('input_data_clean/BOD_DF.csv')

In [4]:
df = df.drop('Unnamed: 0', axis = 1)

liquidity              5
net_income             5
num_employees          5
market_value           9
debt_to_equity         0
assets_in_place        0
capex_by_assets        5
return_on_equity       5

In [22]:
df

,gvkey,ticker,total_sec,othcomp,noneq_incent,cash_fees,stock_awards,option_awards,spcode,cusip,...,size_category,signature_index,liquidity,net_income,num_employees,market_value,debt_to_equity,assets_in_place,capex_by_assets,return_on_equity
0,1045,AAL,47.951,0.951,0.0,47.000,0.000,0.0,SP,02376R10,...,Tiny,589b2d914f25e0a1ff8f707f7aa52096,-0.077408,-471.0,78.25,2597.5755,-7.359442,1.064931,0.078205,-0.018774
1,1045,AAL,0.000,0.000,0.0,0.000,0.000,0.0,SP,02376R10,...,Medium,436a3154f7acadd68f77107364944857,-0.078539,-1979.0,80.10,117.3438,-4.353677,1.042184,0.067511,-0.082984
2,1045,AAL,418.608,36.108,0.0,102.500,280.000,0.0,SP,02376R10,...,Big,dc94df973b47ec03bf615d54bd90e720,-0.094938,-1876.0,77.75,266.5571,-3.943533,1.030753,0.080306,-0.079796
3,1045,AAL,286.838,29.338,0.0,117.500,140.000,0.0,SP,02376R10,...,Big,c2357bce3ae6160bca4e3155a24b1a0a,0.012229,-1834.0,110.40,6591.9923,-16.480776,0.718861,0.073655,-0.043380
4,1045,AAL,317.368,32.368,0.0,135.000,150.000,0.0,SP,02376R10,...,Big,7abb44613cbb465cef913dbfd121155a,-0.030225,2882.0,113.30,37405.5843,20.658090,0.807452,0.121336,0.065843
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8768,316056,ALLE,290.810,20.754,0.0,200.000,70.056,0.0,SP,G0176J10,...,Medium,9a2552c4e1a18391ae83d6a74537a7b6,0.218546,31.0,8.00,4243.5215,-23.451613,0.287489,0.010203,0.015657
8769,316056,ALLE,236.508,0.000,0.0,166.500,70.008,0.0,SP,G0176J10,...,Medium,c5aa2527abdb80465777f4eeb1bce3fc,0.219505,175.2,8.50,5314.7873,-416.125000,0.291086,0.025547,0.086909
8770,316056,ALLE,44.511,0.000,0.0,44.511,0.000,0.0,SP,G0176J10,...,Medium,b33c9610b47875a2cebb9d47b97dd758,0.126023,153.9,9.40,6327.7267,88.109375,0.269768,0.015403,0.067343
8771,316056,ALLE,240.033,0.000,0.0,140.000,100.033,0.0,SP,G0176J10,...,Medium,46be5701765385ac27f8a4d0adabf5f6,0.177850,229.1,9.40,6097.5360,18.808473,0.284951,0.018911,0.101940
8772,316056,ALLE,240.067,0.000,0.0,140.000,100.067,0.0,SP,G0176J10,...,Big,34e1cc2365b0a6eeed12fae0cebc08de,0.224980,273.3,10.00,7563.1327,5.319970,0.278482,0.019394,0.107514

In [7]:
df.columns

Index(['gvkey', 'ticker', 'total_sec', 'othcomp', 'noneq_incent', 'cash_fees',
       'stock_awards', 'option_awards', 'spcode', 'cusip', 'coname', 'year',
       'total_director_comp', 'total_othcomp', 'total_noneq_incent',
       'total_cash_fees', 'total_stock_awards', 'total_option_awards',
       'mkvalt', 'size_category', 'signature_index', 'liquidity', 'net_income',
       'num_employees', 'market_value', 'debt_to_equity', 'assets_in_place',
       'capex_by_assets', 'return_on_equity'],
      dtype='object')

In [20]:
df.loc[df['liquidity'].isna()]

,gvkey,ticker,total_sec,othcomp,noneq_incent,cash_fees,stock_awards,option_awards,spcode,cusip,...,size_category,signature_index,liquidity,net_income,num_employees,market_value,debt_to_equity,assets_in_place,capex_by_assets,return_on_equity
80,1447,AXP,284.371,34.371,0.0,100.0,150.00,0.0,SP,02581610,...,Big,9c59c959ede929ae8d665041a9e7e567,NaN,NaN,61.0,51375.2400,8.059889,0.050244,NaN,NaN
81,1447,AXP,284.371,34.371,0.0,100.0,150.00,0.0,SP,02581610,...,Big,9c59c959ede929ae8d665041a9e7e567,NaN,NaN,61.0,51375.2400,8.059889,0.050244,NaN,NaN
82,1447,AXP,284.371,34.371,0.0,100.0,150.00,0.0,SP,02581610,...,Big,9c59c959ede929ae8d665041a9e7e567,NaN,NaN,61.0,51375.2400,8.059889,0.050244,NaN,NaN
83,1447,AXP,284.371,34.371,0.0,100.0,150.00,0.0,SP,02581610,...,Big,9c59c959ede929ae8d665041a9e7e567,NaN,NaN,61.0,51375.2400,8.059889,0.050244,NaN,NaN
84,1447,AXP,284.371,34.371,0.0,100.0,150.00,0.0,SP,02581610,...,Big,31c38e36aca0401707bcb904ee7e686b,NaN,NaN,61.0,51375.2400,8.059889,0.050244,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8416,177376,DFS,284.990,0.000,0.0,135.0,149.99,0.0,SP,25470910,...,Big,f38b4212f2bd3ed110636262986037ec,NaN,NaN,16.5,27531.2064,8.189038,0.021571,NaN,NaN
8417,177376,DFS,284.990,0.000,0.0,135.0,149.99,0.0,SP,25470910,...,Big,3be8773b46077c65211e8c5d66f92b7a,NaN,NaN,16.5,27531.2064,8.189038,0.021571,NaN,NaN
8418,177376,DFS,284.990,0.000,0.0,135.0,149.99,0.0,SP,25470910,...,Big,3be8773b46077c65211e8c5d66f92b7a,NaN,NaN,16.5,27531.2064,8.189038,0.021571,NaN,NaN
8419,177376,DFS,284.990,0.000,0.0,135.0,149.99,0.0,SP,25470910,...,Big,3be8773b46077c65211e8c5d66f92b7a,NaN,NaN,16.5,27531.2064,8.189038,0.021571,NaN,NaN
8420,177376,DFS,284.990,0.000,0.0,135.0,149.99,0.0,SP,25470910,...,Big,3be8773b46077c65211e8c5d66f92b7a,NaN,NaN,16.5,27531.2064,8.189038,0.021571,NaN,NaN

In [21]:
df.loc[df['net_income'].isna()]

,gvkey,ticker,total_sec,othcomp,noneq_incent,cash_fees,stock_awards,option_awards,spcode,cusip,...,size_category,signature_index,liquidity,net_income,num_employees,market_value,debt_to_equity,assets_in_place,capex_by_assets,return_on_equity
80,1447,AXP,284.371,34.371,0.0,100.0,150.000,0.0,SP,02581610,...,Big,9c59c959ede929ae8d665041a9e7e567,NaN,NaN,61.0,51375.2400,8.059889,0.050244,NaN,NaN
81,1447,AXP,284.371,34.371,0.0,100.0,150.000,0.0,SP,02581610,...,Big,9c59c959ede929ae8d665041a9e7e567,NaN,NaN,61.0,51375.2400,8.059889,0.050244,NaN,NaN
82,1447,AXP,284.371,34.371,0.0,100.0,150.000,0.0,SP,02581610,...,Big,9c59c959ede929ae8d665041a9e7e567,NaN,NaN,61.0,51375.2400,8.059889,0.050244,NaN,NaN
83,1447,AXP,284.371,34.371,0.0,100.0,150.000,0.0,SP,02581610,...,Big,9c59c959ede929ae8d665041a9e7e567,NaN,NaN,61.0,51375.2400,8.059889,0.050244,NaN,NaN
84,1447,AXP,284.371,34.371,0.0,100.0,150.000,0.0,SP,02581610,...,Big,31c38e36aca0401707bcb904ee7e686b,NaN,NaN,61.0,51375.2400,8.059889,0.050244,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8753,260774,CBRE,299.984,0.000,0.0,100.0,199.984,0.0,SP,12504L10,...,Big,3925e44b9223937b67334f88cdcbce50,0.073659,NaN,80.0,14701.9693,1.842122,0.119858,NaN,NaN
8754,260774,CBRE,299.984,0.000,0.0,100.0,199.984,0.0,SP,12504L10,...,Big,c2b6fd79130f53604179f8e0e7a8db15,0.073659,NaN,80.0,14701.9693,1.842122,0.119858,NaN,NaN
8755,260774,CBRE,299.984,0.000,0.0,100.0,199.984,0.0,SP,12504L10,...,Big,c2b6fd79130f53604179f8e0e7a8db15,0.073659,NaN,80.0,14701.9693,1.842122,0.119858,NaN,NaN
8756,260774,CBRE,299.984,0.000,0.0,100.0,199.984,0.0,SP,12504L10,...,Big,c2b6fd79130f53604179f8e0e7a8db15,0.073659,NaN,80.0,14701.9693,1.842122,0.119858,NaN,NaN
8757,260774,CBRE,299.984,0.000,0.0,100.0,199.984,0.0,SP,12504L10,...,Big,c2b6fd79130f53604179f8e0e7a8db15,0.073659,NaN,80.0,14701.9693,1.842122,0.119858,NaN,NaN

In [9]:
df[df['ticker','year','liquidity', 'net_income', 'num_employees', 'market_value', 'capex_by_assets', 'return_on_equity']==0]

KeyError: ('ticker', 'year', 'liquidity', 'net_income', 'num_employees', 'market_value', 'capex_by_assets', 'return_on_equity')